package/force-app/main/default/objects/Migration__c/Migration__c.object-meta.xml
<CustomObject>
    <description>Represents a migration that has been applied to an org</description>
    <label>Migration</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Migration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/force-app/main/default/objects/Migration__c/fields/Checksum__c.field-meta.xml
<CustomField>
    <fullName>Checksum__c</fullName>
    <description>A checksum of the migration script&apos;s contents, used to detect changes in scripts after they have been run.</description>
    <label>Checksum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description of the migration</description>
    <label>Description</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Installed_On__c.field-meta.xml
<CustomField>
    <fullName>Installed_On__c</fullName>
    <description>The date and time at which the migration was run</description>
    <label>Installed On</label>
    <type>DateTime</type>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <description>The namespace prefix or (if the package doesn&apos;t have a namespace prefix) a unique identifier of the package for which the migration was run. Migration versions are unique within the scope of a package.</description>
    <label>Package</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <description>The file name of the script that holds the instructions for this migration.</description>
    <label>Script</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the migration, i.e. whether it was successful or failed.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of migration. Currently only Apex migrations are supported.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APEX</fullName>
                <default>true</default>
                <label>Apex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

package/force-app/main/default/objects/Migration__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of a migration. Version number is unique within a package&apos;s migrations.</description>
    <label>Version</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

package/force-app/main/default/classes/migration/MigrationSelector.cls
public with sharing class MigrationSelector {
    
    public List<Migration__c> selectMigrationsByPackageNameAndVersion(String packageName, List<Integer> versions) {
        return [ 
                SELECT Checksum__c, Description__c, Installed_On__c, Package__c, Script__c, Type__c, Version__c, Status__c
                FROM Migration__c 
                WHERE 
                    Package__c = :packageName AND 
                    Version__c IN :versions
                ORDER BY Version__c
        ];
    }

    public List<Migration__c> selectMigrationsByPackageNameAndId(String packageName, List<Id> ids) {
        return [
                SELECT Checksum__c, Description__c, Installed_On__c, Package__c, Script__c, Type__c, Version__c, Status__c
                FROM Migration__c
                WHERE
                    Package__c = :packageName AND
                    Id IN :ids
                ORDER BY Version__c
        ];
    }

    public List<Migration__c> selectMigrationsByPackageName(String packageName) {
        return [ 
                SELECT Checksum__c, Description__c, Installed_On__c, Package__c, Script__c, Type__c, Version__c, Status__c 
                FROM Migration__c 
                WHERE 
                        Package__c = :packageName
                ORDER BY Version__c
        ];
    }

    public List<Migration__c> selectMigrationsByPackageNameAndStatus(String packageName, List<String> statuses) {
        return [
                SELECT Checksum__c, Description__c, Installed_On__c, Package__c, Script__c, Type__c, Version__c, Status__c
                FROM Migration__c
                WHERE
                        Package__c = :packageName AND
                        Status__c IN :statuses
                ORDER BY Version__c
                        
        ];
    }

    public List<String> selectUniquePackages() {
        List<AggregateResult> migrations = [ SELECT Package__c FROM Migration__c GROUP BY Package__c ];
        List<String> packages = new List<String>();
        for (AggregateResult migration : migrations) {
            packages.add((String) migration.get('m7n__Package__c'));
        }
        return packages;
    }

}